### ISSUE TITLE
Sandbox Prod and Test Endpoint Usage with Client

### ISSUE THREAD

**Issue by venkatsep14** [TeamQuicko/sandbox-client-java#1]
Hi Team,

Endpoint is hardcoded and we can not use between different environments. PROD_API_ENDPOINT. Could you please make this in a way that it could retrieve from the Environment variable or make it as an option to be passed with client so that we can use the test and production environment accordingly.

Let me know if you guys want me to do a pull request I am happy to do that.

Thanks
Venkat

**Comment by TeamQuicko** [comment]
Hi Venkat,
Thank you. With latest release of v1.0.2, we have added the support for UAT environment. You will have to use test credentials while initializing the API client to consume the test endpoints.
